"""Structural protocols for instance and store interfaces.

Enables future cloud backends (e.g. CloudInstance backed by R2/D1)
without coupling handlers to concrete SQLite implementations.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Protocol

from cruxible_core.config.schema import CoreConfig
from cruxible_core.feedback.types import FeedbackRecord, OutcomeRecord
from cruxible_core.graph.entity_graph import EntityGraph
from cruxible_core.group.types import CandidateGroup, CandidateMember
from cruxible_core.provider.types import ExecutionTrace
from cruxible_core.receipt.types import Receipt
from cruxible_core.snapshot.types import WorldSnapshot


class ReceiptStoreProtocol(Protocol):
    """Minimal interface handlers use on the receipt store."""

    def save_receipt(self, receipt: Receipt) -> str: ...
    def get_receipt(self, receipt_id: str) -> Receipt | None: ...
    def save_trace(self, trace: ExecutionTrace) -> str: ...
    def get_trace(self, trace_id: str) -> ExecutionTrace | None: ...
    def list_traces(
        self,
        *,
        workflow_name: str | None = None,
        provider_name: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[dict[str, Any]]: ...
    def list_receipts(
        self,
        *,
        query_name: str | None = None,
        operation_type: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[dict[str, Any]]: ...
    def count_receipts(
        self, *, query_name: str | None = None, operation_type: str | None = None
    ) -> int: ...
    def close(self) -> None: ...


class FeedbackStoreProtocol(Protocol):
    """Minimal interface handlers use on the feedback store."""

    def save_feedback(self, record: FeedbackRecord) -> str: ...
    def list_feedback(
        self, *, receipt_id: str | None = None, limit: int = 50
    ) -> list[FeedbackRecord]: ...
    def count_feedback(self, *, receipt_id: str | None = None) -> int: ...
    def save_outcome(self, record: OutcomeRecord) -> str: ...
    def list_outcomes(
        self, *, receipt_id: str | None = None, limit: int = 50
    ) -> list[OutcomeRecord]: ...
    def count_outcomes(self, *, receipt_id: str | None = None) -> int: ...
    def close(self) -> None: ...


class GroupStoreProtocol(Protocol):
    """Minimal interface for group store operations."""

    def get_group(self, group_id: str) -> CandidateGroup | None: ...
    def list_groups(
        self,
        *,
        relationship_type: str | None = None,
        status: str | None = None,
        limit: int = 50,
    ) -> list[CandidateGroup]: ...
    def count_groups(
        self,
        *,
        relationship_type: str | None = None,
        status: str | None = None,
    ) -> int: ...
    def save_group(self, group: CandidateGroup) -> str: ...
    def save_members(self, group_id: str, members: list[CandidateMember]) -> None: ...
    def get_members(self, group_id: str) -> list[CandidateMember]: ...
    def save_resolution(
        self,
        relationship_type: str,
        signature: str,
        action: str,
        rationale: str,
        thesis_text: str,
        thesis_facts: dict[str, Any],
        analysis_state: dict[str, Any],
        resolved_by: str,
        trust_status: str = "watch",
        confirmed: bool = False,
    ) -> str: ...
    def confirm_resolution(self, resolution_id: str, trust_status: str | None = None) -> None: ...
    def get_resolution(self, resolution_id: str) -> dict[str, Any] | None: ...
    def find_resolution(
        self,
        relationship_type: str,
        signature: str,
        action: str | None = None,
        confirmed: bool | None = None,
    ) -> dict[str, Any] | None: ...
    def list_resolutions(
        self,
        *,
        relationship_type: str | None = None,
        action: str | None = None,
        limit: int = 50,
    ) -> list[dict[str, Any]]: ...
    def update_group_status(
        self, group_id: str, status: str, resolution_id: str | None = None
    ) -> bool: ...
    def update_resolution_trust_status(
        self, resolution_id: str, trust_status: str, trust_reason: str = ""
    ) -> bool: ...
    @contextmanager
    def transaction(self) -> Iterator[None]: ...
    def close(self) -> None: ...


class InstanceProtocol(Protocol):
    """Minimal interface handlers use on a cruxible instance."""

    def get_root_path(self) -> Path: ...
    def get_instance_dir(self) -> Path: ...
    def get_config_path(self) -> Path: ...
    def load_config(self) -> CoreConfig: ...
    def save_config(self, config: CoreConfig) -> None: ...
    def load_graph(self) -> EntityGraph: ...
    def save_graph(self, graph: EntityGraph) -> None: ...
    def invalidate_graph_cache(self) -> None: ...
    def create_snapshot(self, label: str | None = None) -> WorldSnapshot: ...
    def get_snapshot(self, snapshot_id: str) -> WorldSnapshot | None: ...
    def list_snapshots(self) -> list[WorldSnapshot]: ...
    def get_receipt_store(self) -> ReceiptStoreProtocol: ...
    def get_feedback_store(self) -> FeedbackStoreProtocol: ...
    def get_group_store(self) -> GroupStoreProtocol: ...
