"""Structural protocols for instance and store interfaces.

Enables future cloud backends (e.g. CloudInstance backed by R2/D1)
without coupling handlers to concrete SQLite implementations.
"""

from __future__ import annotations

from typing import Any, Protocol

from cruxible_core.config.schema import CoreConfig
from cruxible_core.feedback.types import FeedbackRecord, OutcomeRecord
from cruxible_core.graph.entity_graph import EntityGraph
from cruxible_core.receipt.types import Receipt


class ReceiptStoreProtocol(Protocol):
    """Minimal interface handlers use on the receipt store."""

    def save_receipt(self, receipt: Receipt) -> str: ...
    def get_receipt(self, receipt_id: str) -> Receipt | None: ...
    def list_receipts(
        self,
        *,
        query_name: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[dict[str, Any]]: ...
    def count_receipts(self, *, query_name: str | None = None) -> int: ...
    def close(self) -> None: ...


class FeedbackStoreProtocol(Protocol):
    """Minimal interface handlers use on the feedback store."""

    def save_feedback(self, record: FeedbackRecord) -> str: ...
    def list_feedback(
        self, *, receipt_id: str | None = None, limit: int = 50
    ) -> list[FeedbackRecord]: ...
    def count_feedback(self, *, receipt_id: str | None = None) -> int: ...
    def save_outcome(self, record: OutcomeRecord) -> str: ...
    def list_outcomes(
        self, *, receipt_id: str | None = None, limit: int = 50
    ) -> list[OutcomeRecord]: ...
    def count_outcomes(self, *, receipt_id: str | None = None) -> int: ...
    def close(self) -> None: ...


class InstanceProtocol(Protocol):
    """Minimal interface handlers use on a cruxible instance."""

    def load_config(self) -> CoreConfig: ...
    def save_config(self, config: CoreConfig) -> None: ...
    def load_graph(self) -> EntityGraph: ...
    def save_graph(self, graph: EntityGraph) -> None: ...
    def get_receipt_store(self) -> ReceiptStoreProtocol: ...
    def get_feedback_store(self) -> FeedbackStoreProtocol: ...
