"""Shared service layer — the execution contract behind CLI, MCP, and REST/SDK.

Every product operation goes through this package. Callers (CLI commands, MCP
handlers, REST endpoints) are thin wrappers that handle I/O formatting,
permission checks, and protocol-specific concerns.
"""

from cruxible_core.service.analysis import (
    service_analyze_feedback,
    service_analyze_outcomes,
    service_evaluate,
    service_find_candidates,
)
from cruxible_core.service.execution import (
    service_apply_workflow,
    service_lock,
    service_plan,
    service_propose_workflow,
    service_run,
    service_test,
)
from cruxible_core.service.feedback import (
    service_feedback,
    service_feedback_batch,
    service_get_outcome_profile,
    service_outcome,
)
from cruxible_core.service.groups import (
    derive_review_priority,
    service_get_group,
    service_list_groups,
    service_list_resolutions,
    service_propose_group,
    service_resolve_group,
    service_update_trust_status,
)
from cruxible_core.service.lifecycle import (
    service_init,
    service_reload_config,
    service_validate,
)
from cruxible_core.service.mutations import (
    service_add_entities,
    service_add_relationships,
    service_ingest,
)
from cruxible_core.service.queries import (
    service_get_entity,
    service_get_receipt,
    service_get_relationship,
    service_inspect_entity,
    service_list,
    service_query,
    service_sample,
    service_schema,
    service_stats,
)
from cruxible_core.service.snapshots import (
    service_create_snapshot,
    service_fork_snapshot,
    service_list_snapshots,
)
from cruxible_core.service.types import (
    AddEntityResult,
    AddRelationshipResult,
    AnalyzeFeedbackResult,
    AnalyzeOutcomesResult,
    ApplyWorkflowResult,
    ConstraintSuggestion,
    DebugPackage,
    DecisionPolicySuggestion,
    EntityUpsertInput,
    FeedbackBatchServiceResult,
    FeedbackGroupSummary,
    FeedbackServiceResult,
    ForkSnapshotResult,
    GetGroupResult,
    IngestResult,
    InitResult,
    InspectEntityResult,
    InspectNeighborResult,
    ListGroupsResult,
    ListResolutionsResult,
    ListResult,
    LockServiceResult,
    OutcomeDecisionPolicySuggestion,
    OutcomeGroupSummary,
    OutcomeProviderFixCandidate,
    OutcomeServiceResult,
    PlanServiceResult,
    ProposeGroupResult,
    ProposeWorkflowResult,
    ProviderFixCandidate,
    QualityCheckCandidate,
    QueryParamHints,
    QueryPolicySuggestion,
    QueryServiceResult,
    RelationshipUpsertInput,
    ReloadConfigResult,
    ResolveGroupResult,
    RunServiceResult,
    SnapshotCreateResult,
    SnapshotListResult,
    StatsServiceResult,
    TestServiceResult,
    TrustAdjustmentSuggestion,
    UncodedFeedbackExample,
    UncodedOutcomeExample,
    ValidateServiceResult,
    WorldForkResult,
    WorldPublishResult,
    WorldPullApplyResult,
    WorldPullPreviewResult,
    WorldStatusResult,
)
from cruxible_core.service.world import (
    service_fork_world,
    service_publish_world,
    service_pull_world_apply,
    service_pull_world_preview,
    service_world_status,
)

__all__ = [
    # Types
    "AddEntityResult",
    "AddRelationshipResult",
    "ApplyWorkflowResult",
    "AnalyzeFeedbackResult",
    "AnalyzeOutcomesResult",
    "EntityUpsertInput",
    "ConstraintSuggestion",
    "DecisionPolicySuggestion",
    "DebugPackage",
    "FeedbackBatchServiceResult",
    "FeedbackGroupSummary",
    "FeedbackServiceResult",
    "ForkSnapshotResult",
    "GetGroupResult",
    "IngestResult",
    "InspectEntityResult",
    "InspectNeighborResult",
    "InitResult",
    "LockServiceResult",
    "WorldForkResult",
    "WorldPublishResult",
    "WorldPullApplyResult",
    "WorldPullPreviewResult",
    "WorldStatusResult",
    "ListGroupsResult",
    "ListResolutionsResult",
    "ListResult",
    "OutcomeServiceResult",
    "OutcomeDecisionPolicySuggestion",
    "OutcomeGroupSummary",
    "OutcomeProviderFixCandidate",
    "PlanServiceResult",
    "ProposeWorkflowResult",
    "ProviderFixCandidate",
    "QueryPolicySuggestion",
    "QualityCheckCandidate",
    "ProposeGroupResult",
    "QueryParamHints",
    "QueryServiceResult",
    "ReloadConfigResult",
    "RelationshipUpsertInput",
    "ResolveGroupResult",
    "RunServiceResult",
    "SnapshotCreateResult",
    "SnapshotListResult",
    "StatsServiceResult",
    "TestServiceResult",
    "TrustAdjustmentSuggestion",
    "UncodedFeedbackExample",
    "UncodedOutcomeExample",
    "ValidateServiceResult",
    # Execution
    "service_lock",
    "service_world_status",
    "service_publish_world",
    "service_fork_world",
    "service_pull_world_preview",
    "service_pull_world_apply",
    "service_plan",
    "service_apply_workflow",
    "service_propose_workflow",
    "service_run",
    "service_test",
    "service_create_snapshot",
    "service_fork_snapshot",
    "service_list_snapshots",
    # Analysis
    "service_evaluate",
    "service_find_candidates",
    "service_analyze_feedback",
    "service_analyze_outcomes",
    # Feedback
    "service_feedback",
    "service_feedback_batch",
    "service_get_outcome_profile",
    "service_outcome",
    # Groups
    "derive_review_priority",
    "service_get_group",
    "service_list_groups",
    "service_list_resolutions",
    "service_propose_group",
    "service_resolve_group",
    "service_update_trust_status",
    # Mutations
    "service_add_entities",
    "service_add_relationships",
    "service_ingest",
    # Queries
    "service_get_entity",
    "service_inspect_entity",
    "service_get_receipt",
    "service_get_relationship",
    "service_init",
    "service_list",
    "service_query",
    "service_reload_config",
    "service_sample",
    "service_schema",
    "service_stats",
    "service_validate",
]
