"""Shared service layer — the execution contract behind CLI, MCP, and REST/SDK.

Every product operation goes through this package. Callers (CLI commands, MCP
handlers, REST endpoints) are thin wrappers that handle I/O formatting,
permission checks, and protocol-specific concerns.
"""

from cruxible_core.service.analysis import (
    service_analyze_feedback,
    service_analyze_outcomes,
    service_config_compatibility_warnings,
    service_evaluate,
    service_find_candidates,
    service_lint,
)
from cruxible_core.service.config_mutations import (
    service_add_constraint,
    service_add_decision_policy,
)
from cruxible_core.service.execution import (
    service_apply_workflow,
    service_lock,
    service_plan,
    service_propose_workflow,
    service_run,
    service_test,
)
from cruxible_core.service.feedback import (
    service_feedback,
    service_feedback_batch,
    service_get_outcome_profile,
    service_outcome,
)
from cruxible_core.service.groups import (
    derive_review_priority,
    service_get_group,
    service_group_status,
    service_list_groups,
    service_list_resolutions,
    service_propose_group,
    service_resolve_group,
    service_update_trust_status,
)
from cruxible_core.service.lifecycle import (
    service_init,
    service_reload_config,
    service_validate,
)
from cruxible_core.service.mutations import (
    service_add_entities,
    service_add_relationships,
    service_ingest,
)
from cruxible_core.service.queries import (
    service_describe_query,
    service_get_entity,
    service_get_receipt,
    service_get_relationship,
    service_inspect_entity,
    service_list,
    service_list_queries,
    service_query,
    service_sample,
    service_schema,
    service_stats,
)
from cruxible_core.service.server import service_server_info
from cruxible_core.service.snapshots import (
    service_create_snapshot,
    service_fork_snapshot,
    service_list_snapshots,
)
from cruxible_core.service.types import (
    AddConstraintServiceResult,
    AddDecisionPolicyServiceResult,
    AddEntityResult,
    AddRelationshipResult,
    AnalyzeFeedbackResult,
    AnalyzeOutcomesResult,
    ApplyWorkflowResult,
    ConstraintSuggestion,
    DebugPackage,
    DecisionPolicySuggestion,
    FeedbackBatchServiceResult,
    FeedbackGroupSummary,
    FeedbackServiceResult,
    ForkSnapshotResult,
    GetGroupResult,
    IngestResult,
    InitResult,
    InspectEntityResult,
    InspectNeighborResult,
    LintServiceResult,
    LintSummary,
    ListGroupsResult,
    ListResolutionsResult,
    ListResult,
    LockServiceResult,
    OutcomeDecisionPolicySuggestion,
    OutcomeGroupSummary,
    OutcomeProviderFixCandidate,
    OutcomeServiceResult,
    PlanServiceResult,
    ProposeGroupResult,
    ProposeWorkflowResult,
    ProviderFixCandidate,
    QualityCheckCandidate,
    QueryDefinitionServiceResult,
    QueryParamHints,
    QueryPolicySuggestion,
    QueryServiceResult,
    ReloadConfigResult,
    ResolveGroupResult,
    RunServiceResult,
    ServerInfoServiceResult,
    SnapshotCreateResult,
    SnapshotListResult,
    StatsServiceResult,
    TestServiceResult,
    TrustAdjustmentSuggestion,
    UncodedFeedbackExample,
    UncodedOutcomeExample,
    ValidateServiceResult,
    WorldForkResult,
    WorldPublishResult,
    WorldPullApplyResult,
    WorldPullPreviewResult,
    WorldStatusResult,
)
from cruxible_core.service.world import (
    service_fork_world,
    service_publish_world,
    service_pull_world_apply,
    service_pull_world_preview,
    service_world_status,
)

__all__ = [
    # Types
    "AddEntityResult",
    "AddConstraintServiceResult",
    "AddDecisionPolicyServiceResult",
    "AddRelationshipResult",
    "ApplyWorkflowResult",
    "AnalyzeFeedbackResult",
    "AnalyzeOutcomesResult",
    "ConstraintSuggestion",
    "DecisionPolicySuggestion",
    "DebugPackage",
    "FeedbackBatchServiceResult",
    "FeedbackGroupSummary",
    "FeedbackServiceResult",
    "ForkSnapshotResult",
    "GetGroupResult",
    "IngestResult",
    "InspectEntityResult",
    "InspectNeighborResult",
    "InitResult",
    "LockServiceResult",
    "WorldForkResult",
    "WorldPublishResult",
    "WorldPullApplyResult",
    "WorldPullPreviewResult",
    "WorldStatusResult",
    "ListGroupsResult",
    "ListResolutionsResult",
    "ListResult",

    "LintServiceResult",
    "LintSummary",
    "OutcomeServiceResult",
    "OutcomeDecisionPolicySuggestion",
    "OutcomeGroupSummary",
    "OutcomeProviderFixCandidate",
    "PlanServiceResult",
    "ProposeWorkflowResult",
    "ProviderFixCandidate",
    "QueryPolicySuggestion",
    "QualityCheckCandidate",
    "ProposeGroupResult",
    "QueryDefinitionServiceResult",
    "QueryParamHints",
    "QueryServiceResult",
    "ReloadConfigResult",
    "ResolveGroupResult",
    "RunServiceResult",
    "ServerInfoServiceResult",
    "SnapshotCreateResult",
    "SnapshotListResult",
    "StatsServiceResult",
    "TestServiceResult",
    "TrustAdjustmentSuggestion",
    "UncodedFeedbackExample",
    "UncodedOutcomeExample",
    "ValidateServiceResult",
    # Execution
    "service_lock",
    "service_world_status",
    "service_publish_world",
    "service_fork_world",
    "service_pull_world_preview",
    "service_pull_world_apply",
    "service_plan",
    "service_apply_workflow",
    "service_propose_workflow",
    "service_run",
    "service_test",
    "service_create_snapshot",
    "service_fork_snapshot",
    "service_list_snapshots",
    # Analysis
    "service_evaluate",
    "service_find_candidates",
    "service_analyze_feedback",
    "service_analyze_outcomes",
    "service_config_compatibility_warnings",
    "service_lint",
    # Feedback
    "service_feedback",
    "service_feedback_batch",
    "service_get_outcome_profile",
    "service_outcome",
    # Groups
    "derive_review_priority",
    "service_get_group",
    "service_group_status",
    "service_list_groups",
    "service_list_resolutions",
    "service_propose_group",
    "service_resolve_group",
    "service_update_trust_status",
    # Mutations
    "service_add_entities",
    "service_add_relationships",
    "service_ingest",
    # Queries
    "service_get_entity",
    "service_inspect_entity",
    "service_get_receipt",
    "service_get_relationship",
    "service_add_constraint",
    "service_add_decision_policy",
    "service_init",
    "service_list",
    "service_list_queries",
    "service_describe_query",
    "service_query",
    "service_reload_config",
    "service_sample",
    "service_schema",
    "service_server_info",
    "service_stats",
    "service_validate",
]
